/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [Identifiant_Contact]
      ,[ID_MYCONSOO]
      ,[EMAIL]
      ,[PRENOM]
      ,[NOM]
      ,[DATE_NAISS]
      ,[VILLE]
      ,[CP]
      ,[DUREE]
      ,[POINTS]
      ,[DATE_CREDIT]
      ,[CODE]
      ,[SEXE]
      ,[AGEclair]
      ,[AGE]
      ,[CSP]
      ,[DPT]
      ,[ZONE]
      ,[TAILLE_FOYER]
      ,[Date_de_creation]
      ,[Dernier_Magasin]
      ,[NB_VISITE]
      ,[NB_PROD]
      ,[RECENCE]
      ,[Rayon]
  FROM [ListesPanel].[dbo].[RET2570_BUT_ProfilingClients_PANEL]