/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [ID_ENOV]
      ,[Nombre]
      ,[TEL1]
      ,[REF_Dossier]
      ,[Raison sociale de l'apporteur]
      ,[Apporteur]
      ,[Societe]
      ,[Chantier]
      ,[Correspondant]
      ,[Groupe]
      ,[Mail]
      ,[NOM_DOSSIER]
      ,[Phase]
      ,[Segmentation]
      ,[MEL2]
      ,[MEL]
      ,[Date_MEL]
      ,[TYPE]
      ,[Usage]
      ,[Ville]
  FROM [ListesExternes].[dbo].[BFA0178_BPCE_Lease_CBI_2025]