/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [ID_ENOV]
      ,[CODE_ACTION]
      ,[SOURCE]
      ,[SOURCE_EXPLICATION_AC]
      ,[EMAIL]
      ,[EMAIL_COMPT_AC]
      ,[TEL_PORT_PRIO_1]
      ,[PORT_COMP_AC]
      ,[COMP_F]
      ,[ID_PERSONNE]
      ,[ID_CONTRAT]
      ,[ID_BP_SYMPH]
      ,[ID_LOCAL]
      ,[CIVILITE]
      ,[CONTACT]
      ,[NOM]
      ,[PRENOM]
      ,[ANCIENNETE_LOCAL]
      ,[TYPE_RESIDENCE]
      ,[STATUT_OCCUPATION]
      ,[ENERGIE_LOCAL]
      ,[MODE_CHAUFFAGE]
      ,[DATE_RECV_PROCH_FACTU]
      ,[DATE_SOUS]
      ,[FREQUENCE_FACTURATION]
      ,[CANAL_VENTE_PC]
      ,[DATA_SOUS_CEL]
      ,[DATA_SOUS_FEL]
      ,[DATE_DEBUT]
      ,[DATE_FIN]
      ,[NO_VOIE]
      ,[LIB_VOIE]
      ,[COD_POSTAL]
      ,[COMMUNE]
      ,[DATE_EMMENAGE_LOCAL]
  FROM [ListesExternes].[dbo].[ENE0097_ENGIE_Post_test_CourrierOffreElec]