/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [MailId]
      ,[EmailAddress]
      ,[SurveyId]
      ,[ListId]
      ,[ContactId]
      ,[Type]
      ,[Time]
      ,[SmtpUsed]
      ,[Sender]
      ,[Subject]
      ,[MailResult]
      ,[BouncedTime]
      ,[BouncedReason]
      ,[BouncedMail]
      ,[Cc]
      ,[Bcc]
      ,[ReplyTo]
  FROM [Askia_Statistics].[dbo].[Statistic_Mail]