/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [ID_ENOV]
      ,[PRODUIT_FINAL_0]
      ,[CODE_ID_Par personne]
      ,[ID_Par personne]
      ,[CIVILITE]
      ,[NOM]
      ,[PRENOM]
      ,[SEXE_0]
      ,[DATNAI]
      ,[NB_BE]
      ,[NB_BC]
      ,[NOVOI]
      ,[NATVOI]
      ,[LIBVOI]
      ,[LIEUDIT]
      ,[CODPTL]
      ,[LOC]
      ,[CODPAYS]
      ,[FIXE_FINAL]
      ,[MOBILE_1]
      ,[MOBILE_2]
      ,[ADRESSE_MAIL]
      ,[DEPT]
      ,[OFFRE]
      ,[DATE ADH]
      ,[PRODUIT_FINAL]
      ,[LIB_PRODUIT]
      ,[LIB_PRODUIT_2]
      ,[TRANCHE_AGE]
      ,[AGE_F]
      ,[AGE_CLAIR]
      ,[SEXE]
      ,[TEL_1]
      ,[ADR_TYPE]
  FROM [ListesExternes].[dbo].[BFA0128_MGEN_Baro_ConventionDeParticipation]