/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [AskInterview]
      ,[AskSurveyId]
      ,[AskSurveyPosition]
      ,[AskSurveyInterviewId]
      ,[AskSurveyInterviewState]
      ,[AskTaskInterviewGuid]
      ,[AskAppManual]
      ,[AskAppTimeUTC]
      ,[AskAppImportance]
      ,[AskAppMessage]
      ,[AskAppAgentId]
      ,[AskAppForAgentOnly]
      ,[AskCallAcknowledgementMessage]
      ,[AskPriority]
      ,[AskCallNow]
      ,[AskQuotaCategory]
      ,[AskSkillCategory]
      ,[AskQuotaReached]
      ,[AskOrderPriority]
      ,[AskDoNotCallListId]
      ,[AskDoNotMailListId]
      ,[AskInterviewFiltered]
      ,[AskTimeZoneId]
      ,[AskMode]
      ,[AskInCall]
      ,[AskDerivation]
      ,[AskLastRecoverUTC]
      ,[AskIsOverCallback]
      ,[AskCallCount]
      ,[AskTimeAvailableUTC]
      ,[AskShiftAvailable]
      ,[AskLastTelephonyResponseUTC]
      ,[AskLastTelephonyResponseUTCOffsetAgent]
      ,[AskLastTelephonyResponseUTCOffsetRespondent]
      ,[AskLastTelephonyShift]
      ,[AskLastTelephonyShiftPercentage]
      ,[AskLastTelephonyResult]
      ,[AskLastTelephonySubResult]
      ,[AskTelephonyWorkingPriority]
      ,[AskCallbackMinutesSuspended]
      ,[AskLastWebResponseUTC]
      ,[AskLastWebResponseUTCOffsetRespondent]
      ,[AskLastWebResult]
      ,[AskWebWorkingPriority]
      ,[TELEPHONE]
      ,[AskHashDNC_TELEPHONE]
      ,[ID_ENOV]
      ,[EMAIL]
      ,[AskHashDNC_EMAIL]
      ,[CLIENT PREDORMANT OU DORMANT]
      ,[CODE_DEPT]
      ,[CODE_DPT]
      ,[ContactID]
      ,[Fichier d'origine]
      ,[First and Last Name]
      ,[FL_STOP_MAILING]
      ,[FL_STOP_PHONING]
      ,[KO_CNTC_EMAIL]
      ,[KO_CNTC_TEL_PORT]
      ,[LB_CONT]
      ,[LIB_UDA5]
      ,[Mobile Phone]
      ,[Mode de sollicitation]
      ,[MODE_SOLLICITATION]
      ,[NOM]
      ,[PRENOM]
      ,[SMS Opt-out]
      ,[SmsOptIn (App_v1)]
      ,[TRANCHE_AGE]
      ,[TYPE_ENERGIE]
      ,[UDA5]
      ,[UDA51]
      ,[UDA9]
      ,[Relance1]
  FROM [Askia_Lists].[dbo].[AskList12435]