/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [ID_MYCONSOO]
      ,[EMAIL]
      ,[PRENOM]
      ,[NOM]
      ,[DATE_NAISS]
      ,[VILLE]
      ,[CP]
      ,[DUREE]
      ,[POINTS]
      ,[DATE_CREDIT]
      ,[CODE]
      ,[SEXE]
      ,[AGEclair]
      ,[AGE]
      ,[CSP]
      ,[DPT]
      ,[ZONE]
      ,[TAILLE_FOYER]
      ,[VAGUE]
  FROM [ListesPanel].[dbo].[ENO0103_ENOV_Baro_Inflation_Prix_V6]

  UPDATE [ListesPanel].[dbo].[ENO0103_ENOV_Baro_Inflation_Prix_V6]
  SET [DATE_CREDIT] = '20/02/2025';