/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [ID]
      ,[PHONE]
      ,[EMAIL]
      ,[NOM]
      ,[PRENOM]
      ,[CP]
      ,[COMMUNE]
      ,[AGE_CALCUL]
      ,[ZONE]
      ,[SEXE]
      ,[AGE]
      ,[PCS]
      ,[Broker]
      ,[MODE_RECUEIL]
  FROM [ListesExternes].[dbo].['TSP1791_TISSEO-VOYAGEURS_Baro_v50']