/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (10000) [ID_MYCONSOO]
      ,[EMAIL]
      ,[PRENOM]
      ,[NOM]
      ,[DATE_NAISS]
      ,[VILLE]
      ,[CP]
      ,[DUREE]
      ,[POINTS]
      ,[DATE_CREDIT]
      ,[CODE]
      ,[SEXE]
      ,[AGEclair]
      ,[AGE]
      ,[CSP]
      ,[DPT]
      ,[ZONE]
      ,[TAILLE_FOYER]
      ,[LISTE_NOIRE]
      ,[TYPE]
  FROM [ListesPanel].[dbo].[BFA0144_BPCE_SeniorsEtCreditConsommation_PANEL]

  ALTER TABLE [ListesPanel].[dbo].[BFA0144_BPCE_SeniorsEtCreditConsommation_PANEL]
  ADD [ccaPhone] NVARCHAR(255);
