/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (13000) [ID_MYCONSOO]
      ,[EMAIL]
      ,[PRENOM]
      ,[NOM]
      ,[DATE_NAISS]
      ,[VILLE]
      ,[CP]
      ,[DUREE]
      ,[POINTS]
      ,[DATE_CREDIT]
      ,[CODE]
      ,[SEXE]
      ,[AGEclair]
      ,[AGE]
      ,[CSP]
      ,[DPT]
      ,[ZONE]
      ,[TAILLE_FOYER]
      ,[LISTE_NOIRE]
  FROM [ListesPanel].[dbo].[RET2587_5ASEC_Tracker_NotoImage]