/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (5000) [NUM]
      ,[ID]
      ,[PHONE]
      ,[EMAIL]
      ,[NOM]
      ,[PRENOM]
      ,[CP]
      ,[COMMUNE]
      ,[AGE_CALCUL]
      ,[ZONE]
      ,[SEXE]
      ,[AGE]
      ,[PCS]
      ,[Broker]
      ,[MODE_RECUEIL]
  FROM [ListesExternes].[dbo].[TSP1864_TISSEO-VOYAGEURS_Baro_v54]