/****** Script de la commande SelectTopNRows à partir de SSMS  ******/
SELECT TOP (1000) [ID_ENOV]
      ,[ID_RETAIL]
      ,[ENTREPRISE]
      ,[NOM]
      ,[PRENOM]
      ,[ADRESSE_MAIL]
      ,[TELEPHONE]
      ,[NUMERO_TEL]
      ,[TYPE_TEL]
      ,[DEPARTEMENT]
      ,[TYPE_DE_DISTRIBUTEUR]
      ,[FONCTION]
      ,[CLASSIFICATION]
      ,[CA_RECODE]
      ,[FAMILLE_RECOD]
      ,[STATUT]
  FROM [ListesExternes].[dbo].[RET2554_TMP-CONVERT_SatisfactionJouplast]